// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package microphone

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.MicrophoneApiServer	and presents it as a traits.MicrophoneApiClient
func WrapApi(server traits.MicrophoneApiServer) traits.MicrophoneApiClient {
	conn := wrap.ServerToClient(traits.MicrophoneApi_ServiceDesc, server)
	client := traits.NewMicrophoneApiClient(conn)
	return &apiWrapper{
		MicrophoneApiClient: client,
		server:              server,
	}
}

type apiWrapper struct {
	traits.MicrophoneApiClient

	server traits.MicrophoneApiServer
}

// compile time check that we implement the interface we need
var _ traits.MicrophoneApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.MicrophoneApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
