// Code generated by protoc-gen-router. DO NOT EDIT.

package microphone

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.MicrophoneInfoServer that allows routing named requests to specific traits.MicrophoneInfoClient
type InfoRouter struct {
	traits.UnimplementedMicrophoneInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.MicrophoneInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithMicrophoneInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithMicrophoneInfoClientFactory(f func(name string) (traits.MicrophoneInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterMicrophoneInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.MicrophoneInfoClient.
func (r *InfoRouter) Add(name string, client interface{}) interface{} {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.MicrophoneInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client interface{}) bool {
	_, ok := client.(traits.MicrophoneInfoClient)
	return ok
}

func (r *InfoRouter) AddMicrophoneInfoClient(name string, client traits.MicrophoneInfoClient) traits.MicrophoneInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.MicrophoneInfoClient)
}

func (r *InfoRouter) RemoveMicrophoneInfoClient(name string) traits.MicrophoneInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.MicrophoneInfoClient)
}

func (r *InfoRouter) GetMicrophoneInfoClient(name string) (traits.MicrophoneInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.MicrophoneInfoClient), nil
}

func (r *InfoRouter) DescribeGain(ctx context.Context, request *traits.DescribeGainRequest) (*traits.GainSupport, error) {
	child, err := r.GetMicrophoneInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeGain(ctx, request)
}
