// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package microphone

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.MicrophoneInfoServer	and presents it as a traits.MicrophoneInfoClient
func WrapInfo(server traits.MicrophoneInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.MicrophoneInfo_ServiceDesc, server)
	client := traits.NewMicrophoneInfoClient(conn)
	return &InfoWrapper{
		MicrophoneInfoClient: client,
		server:               server,
		conn:                 conn,
		desc:                 traits.MicrophoneInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.MicrophoneInfoClient

	server traits.MicrophoneInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.MicrophoneInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
