// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package microphone

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.MicrophoneInfoServer	and presents it as a traits.MicrophoneInfoClient
func WrapInfo(server traits.MicrophoneInfoServer) traits.MicrophoneInfoClient {
	conn := wrap.ServerToClient(traits.MicrophoneInfo_ServiceDesc, server)
	client := traits.NewMicrophoneInfoClient(conn)
	return &infoWrapper{
		MicrophoneInfoClient: client,
		server:               server,
	}
}

type infoWrapper struct {
	traits.MicrophoneInfoClient

	server traits.MicrophoneInfoServer
}

// compile time check that we implement the interface we need
var _ traits.MicrophoneInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.MicrophoneInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
