// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package airqualitysensor

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.AirQualitySensorApiServer	and presents it as a traits.AirQualitySensorApiClient
func WrapApi(server traits.AirQualitySensorApiServer) traits.AirQualitySensorApiClient {
	conn := wrap.ServerToClient(traits.AirQualitySensorApi_ServiceDesc, server)
	client := traits.NewAirQualitySensorApiClient(conn)
	return &apiWrapper{
		AirQualitySensorApiClient: client,
		server:                    server,
	}
}

type apiWrapper struct {
	traits.AirQualitySensorApiClient

	server traits.AirQualitySensorApiServer
}

// compile time check that we implement the interface we need
var _ traits.AirQualitySensorApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.AirQualitySensorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
