// Code generated by protoc-gen-router. DO NOT EDIT.

package electricpb

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.ElectricApiServer that allows routing named requests to specific traits.ElectricApiClient
type ApiRouter struct {
	traits.UnimplementedElectricApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.ElectricApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithElectricApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithElectricApiClientFactory(f func(name string) (traits.ElectricApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterElectricApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.ElectricApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.ElectricApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(traits.ElectricApiClient)
	return ok
}

func (r *ApiRouter) AddElectricApiClient(name string, client traits.ElectricApiClient) traits.ElectricApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ElectricApiClient)
}

func (r *ApiRouter) RemoveElectricApiClient(name string) traits.ElectricApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ElectricApiClient)
}

func (r *ApiRouter) GetElectricApiClient(name string) (traits.ElectricApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ElectricApiClient), nil
}

func (r *ApiRouter) GetDemand(ctx context.Context, request *traits.GetDemandRequest) (*traits.ElectricDemand, error) {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetDemand(ctx, request)
}

func (r *ApiRouter) PullDemand(request *traits.PullDemandRequest, server traits.ElectricApi_PullDemandServer) error {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullDemand(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullDemandResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) GetActiveMode(ctx context.Context, request *traits.GetActiveModeRequest) (*traits.ElectricMode, error) {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetActiveMode(ctx, request)
}

func (r *ApiRouter) UpdateActiveMode(ctx context.Context, request *traits.UpdateActiveModeRequest) (*traits.ElectricMode, error) {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateActiveMode(ctx, request)
}

func (r *ApiRouter) ClearActiveMode(ctx context.Context, request *traits.ClearActiveModeRequest) (*traits.ElectricMode, error) {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ClearActiveMode(ctx, request)
}

func (r *ApiRouter) PullActiveMode(request *traits.PullActiveModeRequest, server traits.ElectricApi_PullActiveModeServer) error {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullActiveMode(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullActiveModeResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) ListModes(ctx context.Context, request *traits.ListModesRequest) (*traits.ListModesResponse, error) {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ListModes(ctx, request)
}

func (r *ApiRouter) PullModes(request *traits.PullModesRequest, server traits.ElectricApi_PullModesServer) error {
	child, err := r.GetElectricApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullModes(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullModesResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
