// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package occupancysensor

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// Wrap Info	adapts a traits.OccupancySensorInfoServer	and presents it as a traits.OccupancySensorInfoClient
func WrapInfo(server traits.OccupancySensorInfoServer) traits.OccupancySensorInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.OccupancySensorInfoServer
}

// compile time check that we implement the interface we need
var _ traits.OccupancySensorInfoClient = (*infoWrapper)(nil)

func (w *infoWrapper) DescribeOccupancy(ctx context.Context, req *traits.DescribeOccupancyRequest, _ ...grpc.CallOption) (*traits.OccupancySupport, error) {
	return w.server.DescribeOccupancy(ctx, req)
}
