// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package occupancysensor

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.OccupancySensorInfoServer	and presents it as a traits.OccupancySensorInfoClient
func WrapInfo(server traits.OccupancySensorInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.OccupancySensorInfo_ServiceDesc, server)
	client := traits.NewOccupancySensorInfoClient(conn)
	return &InfoWrapper{
		OccupancySensorInfoClient: client,
		server:                    server,
		conn:                      conn,
		desc:                      traits.OccupancySensorInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.OccupancySensorInfoClient

	server traits.OccupancySensorInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.OccupancySensorInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
