// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package occupancysensor

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.OccupancySensorInfoServer	and presents it as a traits.OccupancySensorInfoClient
func WrapInfo(server traits.OccupancySensorInfoServer) traits.OccupancySensorInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.OccupancySensorInfoServer
}

// compile time check that we implement the interface we need
var _ traits.OccupancySensorInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.OccupancySensorInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *infoWrapper) DescribeOccupancy(ctx context.Context, req *traits.DescribeOccupancyRequest, _ ...grpc.CallOption) (*traits.OccupancySupport, error) {
	return w.server.DescribeOccupancy(ctx, req)
}
