// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package airqualitysensorpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.AirQualitySensorApiServer	and presents it as a traits.AirQualitySensorApiClient
func WrapApi(server traits.AirQualitySensorApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.AirQualitySensorApi_ServiceDesc, server)
	client := traits.NewAirQualitySensorApiClient(conn)
	return &ApiWrapper{
		AirQualitySensorApiClient: client,
		server:                    server,
		conn:                      conn,
		desc:                      traits.AirQualitySensorApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.AirQualitySensorApiClient

	server traits.AirQualitySensorApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.AirQualitySensorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
