// Code generated by protoc-gen-router. DO NOT EDIT.

package airqualitysensorpb

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.AirQualitySensorInfoServer that allows routing named requests to specific traits.AirQualitySensorInfoClient
type InfoRouter struct {
	traits.UnimplementedAirQualitySensorInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.AirQualitySensorInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithAirQualitySensorInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithAirQualitySensorInfoClientFactory(f func(name string) (traits.AirQualitySensorInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterAirQualitySensorInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.AirQualitySensorInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.AirQualitySensorInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.AirQualitySensorInfoClient)
	return ok
}

func (r *InfoRouter) AddAirQualitySensorInfoClient(name string, client traits.AirQualitySensorInfoClient) traits.AirQualitySensorInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.AirQualitySensorInfoClient)
}

func (r *InfoRouter) RemoveAirQualitySensorInfoClient(name string) traits.AirQualitySensorInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.AirQualitySensorInfoClient)
}

func (r *InfoRouter) GetAirQualitySensorInfoClient(name string) (traits.AirQualitySensorInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.AirQualitySensorInfoClient), nil
}

func (r *InfoRouter) DescribeAirQuality(ctx context.Context, request *traits.DescribeAirQualityRequest) (*traits.AirQualitySupport, error) {
	child, err := r.GetAirQualitySensorInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeAirQuality(ctx, request)
}
