// Code generated by protoc-gen-router. DO NOT EDIT.

package channel

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.ChannelApiServer that allows routing named requests to specific traits.ChannelApiClient
type ApiRouter struct {
	traits.UnimplementedChannelApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.ChannelApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithChannelApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithChannelApiClientFactory(f func(name string) (traits.ChannelApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterChannelApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.ChannelApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.ChannelApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(traits.ChannelApiClient)
	return ok
}

func (r *ApiRouter) AddChannelApiClient(name string, client traits.ChannelApiClient) traits.ChannelApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ChannelApiClient)
}

func (r *ApiRouter) RemoveChannelApiClient(name string) traits.ChannelApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ChannelApiClient)
}

func (r *ApiRouter) GetChannelApiClient(name string) (traits.ChannelApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ChannelApiClient), nil
}

func (r *ApiRouter) GetChosenChannel(ctx context.Context, request *traits.GetChosenChannelRequest) (*traits.Channel, error) {
	child, err := r.GetChannelApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetChosenChannel(ctx, request)
}

func (r *ApiRouter) ChooseChannel(ctx context.Context, request *traits.ChooseChannelRequest) (*traits.Channel, error) {
	child, err := r.GetChannelApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ChooseChannel(ctx, request)
}

func (r *ApiRouter) AdjustChannel(ctx context.Context, request *traits.AdjustChannelRequest) (*traits.Channel, error) {
	child, err := r.GetChannelApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.AdjustChannel(ctx, request)
}

func (r *ApiRouter) ReturnChannel(ctx context.Context, request *traits.ReturnChannelRequest) (*traits.Channel, error) {
	child, err := r.GetChannelApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ReturnChannel(ctx, request)
}

func (r *ApiRouter) PullChosenChannel(request *traits.PullChosenChannelRequest, server traits.ChannelApi_PullChosenChannelServer) error {
	child, err := r.GetChannelApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullChosenChannel(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullChosenChannelResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
