// Code generated by protoc-gen-router. DO NOT EDIT.

package channel

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.ChannelInfoServer that allows routing named requests to specific traits.ChannelInfoClient
type InfoRouter struct {
	traits.UnimplementedChannelInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.ChannelInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithChannelInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithChannelInfoClientFactory(f func(name string) (traits.ChannelInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterChannelInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.ChannelInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.ChannelInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.ChannelInfoClient)
	return ok
}

func (r *InfoRouter) AddChannelInfoClient(name string, client traits.ChannelInfoClient) traits.ChannelInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ChannelInfoClient)
}

func (r *InfoRouter) RemoveChannelInfoClient(name string) traits.ChannelInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ChannelInfoClient)
}

func (r *InfoRouter) GetChannelInfoClient(name string) (traits.ChannelInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ChannelInfoClient), nil
}

func (r *InfoRouter) DescribeChosenChannel(ctx context.Context, request *traits.DescribeChosenChannelRequest) (*traits.ChosenChannelSupport, error) {
	child, err := r.GetChannelInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeChosenChannel(ctx, request)
}
