// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package airtemperature

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.AirTemperatureApiServer	and presents it as a traits.AirTemperatureApiClient
func WrapApi(server traits.AirTemperatureApiServer) traits.AirTemperatureApiClient {
	conn := wrap.ServerToClient(traits.AirTemperatureApi_ServiceDesc, server)
	client := traits.NewAirTemperatureApiClient(conn)
	return &apiWrapper{
		AirTemperatureApiClient: client,
		server:                  server,
	}
}

type apiWrapper struct {
	traits.AirTemperatureApiClient

	server traits.AirTemperatureApiServer
}

// compile time check that we implement the interface we need
var _ traits.AirTemperatureApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.AirTemperatureApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
