// Code generated by protoc-gen-router. DO NOT EDIT.

package airtemperature

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.AirTemperatureInfoServer that allows routing named requests to specific traits.AirTemperatureInfoClient
type InfoRouter struct {
	traits.UnimplementedAirTemperatureInfoServer

	router *router.Router
}

// compile time check that we implement the interface we need
var _ traits.AirTemperatureInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		router: router.NewRouter(opts...),
	}
}

// WithAirTemperatureInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithAirTemperatureInfoClientFactory(f func(name string) (traits.AirTemperatureInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterAirTemperatureInfoServer(server, r)
}

func (r *InfoRouter) Add(name string, client traits.AirTemperatureInfoClient) traits.AirTemperatureInfoClient {
	res := r.router.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.AirTemperatureInfoClient)
}

func (r *InfoRouter) Remove(name string) traits.AirTemperatureInfoClient {
	res := r.router.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.AirTemperatureInfoClient)
}

func (r *InfoRouter) Has(name string) bool {
	return r.router.Has(name)
}

func (r *InfoRouter) Get(name string) (traits.AirTemperatureInfoClient, error) {
	res, err := r.router.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.AirTemperatureInfoClient), nil
}

func (r *InfoRouter) DescribeAirTemperature(ctx context.Context, request *traits.DescribeAirTemperatureRequest) (*traits.AirTemperatureSupport, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeAirTemperature(ctx, request)
}
