// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package airtemperature

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.AirTemperatureInfoServer	and presents it as a traits.AirTemperatureInfoClient
func WrapInfo(server traits.AirTemperatureInfoServer) traits.AirTemperatureInfoClient {
	conn := wrap.ServerToClient(traits.AirTemperatureInfo_ServiceDesc, server)
	client := traits.NewAirTemperatureInfoClient(conn)
	return &infoWrapper{
		AirTemperatureInfoClient: client,
		server:                   server,
	}
}

type infoWrapper struct {
	traits.AirTemperatureInfoClient

	server traits.AirTemperatureInfoServer
}

// compile time check that we implement the interface we need
var _ traits.AirTemperatureInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.AirTemperatureInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
