// Code generated by protoc-gen-router. DO NOT EDIT.

package airtemperature

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.AirTemperatureInfoServer that allows routing named requests to specific traits.AirTemperatureInfoClient
type InfoRouter struct {
	traits.UnimplementedAirTemperatureInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.AirTemperatureInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithAirTemperatureInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithAirTemperatureInfoClientFactory(f func(name string) (traits.AirTemperatureInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterAirTemperatureInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.AirTemperatureInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.AirTemperatureInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.AirTemperatureInfoClient)
	return ok
}

func (r *InfoRouter) AddAirTemperatureInfoClient(name string, client traits.AirTemperatureInfoClient) traits.AirTemperatureInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.AirTemperatureInfoClient)
}

func (r *InfoRouter) RemoveAirTemperatureInfoClient(name string) traits.AirTemperatureInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.AirTemperatureInfoClient)
}

func (r *InfoRouter) GetAirTemperatureInfoClient(name string) (traits.AirTemperatureInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.AirTemperatureInfoClient), nil
}

func (r *InfoRouter) DescribeAirTemperature(ctx context.Context, request *traits.DescribeAirTemperatureRequest) (*traits.AirTemperatureSupport, error) {
	child, err := r.GetAirTemperatureInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeAirTemperature(ctx, request)
}
