// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package airtemperature

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.AirTemperatureInfoServer	and presents it as a traits.AirTemperatureInfoClient
func WrapInfo(server traits.AirTemperatureInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.AirTemperatureInfo_ServiceDesc, server)
	client := traits.NewAirTemperatureInfoClient(conn)
	return &InfoWrapper{
		AirTemperatureInfoClient: client,
		server:                   server,
		conn:                     conn,
		desc:                     traits.AirTemperatureInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.AirTemperatureInfoClient

	server traits.AirTemperatureInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.AirTemperatureInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
