// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package parentpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.ParentApiServer	and presents it as a traits.ParentApiClient
func WrapApi(server traits.ParentApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.ParentApi_ServiceDesc, server)
	client := traits.NewParentApiClient(conn)
	return &ApiWrapper{
		ParentApiClient: client,
		server:          server,
		conn:            conn,
		desc:            traits.ParentApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.ParentApiClient

	server traits.ParentApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.ParentApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
