// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package parentpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ParentInfoServer	and presents it as a traits.ParentInfoClient
func WrapInfo(server traits.ParentInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.ParentInfo_ServiceDesc, server)
	client := traits.NewParentInfoClient(conn)
	return &InfoWrapper{
		ParentInfoClient: client,
		server:           server,
		conn:             conn,
		desc:             traits.ParentInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.ParentInfoClient

	server traits.ParentInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.ParentInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
