// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package inputselect

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.InputSelectApiServer	and presents it as a traits.InputSelectApiClient
func WrapApi(server traits.InputSelectApiServer) traits.InputSelectApiClient {
	conn := wrap.ServerToClient(traits.InputSelectApi_ServiceDesc, server)
	client := traits.NewInputSelectApiClient(conn)
	return &apiWrapper{
		InputSelectApiClient: client,
		server:               server,
	}
}

type apiWrapper struct {
	traits.InputSelectApiClient

	server traits.InputSelectApiServer
}

// compile time check that we implement the interface we need
var _ traits.InputSelectApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.InputSelectApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
