// Code generated by protoc-gen-router. DO NOT EDIT.

package inputselect

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.InputSelectInfoServer that allows routing named requests to specific traits.InputSelectInfoClient
type InfoRouter struct {
	traits.UnimplementedInputSelectInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.InputSelectInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithInputSelectInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithInputSelectInfoClientFactory(f func(name string) (traits.InputSelectInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterInputSelectInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.InputSelectInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.InputSelectInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.InputSelectInfoClient)
	return ok
}

func (r *InfoRouter) AddInputSelectInfoClient(name string, client traits.InputSelectInfoClient) traits.InputSelectInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.InputSelectInfoClient)
}

func (r *InfoRouter) RemoveInputSelectInfoClient(name string) traits.InputSelectInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.InputSelectInfoClient)
}

func (r *InfoRouter) GetInputSelectInfoClient(name string) (traits.InputSelectInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.InputSelectInfoClient), nil
}

func (r *InfoRouter) DescribeInput(ctx context.Context, request *traits.DescribeInputRequest) (*traits.InputSupport, error) {
	child, err := r.GetInputSelectInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeInput(ctx, request)
}
