// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package inputselect

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.InputSelectInfoServer	and presents it as a traits.InputSelectInfoClient
func WrapInfo(server traits.InputSelectInfoServer) traits.InputSelectInfoClient {
	conn := wrap.ServerToClient(traits.InputSelectInfo_ServiceDesc, server)
	client := traits.NewInputSelectInfoClient(conn)
	return &infoWrapper{
		InputSelectInfoClient: client,
		server:                server,
	}
}

type infoWrapper struct {
	traits.InputSelectInfoClient

	server traits.InputSelectInfoServer
}

// compile time check that we implement the interface we need
var _ traits.InputSelectInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.InputSelectInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
