// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package emergencypb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.EmergencyApiServer	and presents it as a traits.EmergencyApiClient
func WrapApi(server traits.EmergencyApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.EmergencyApi_ServiceDesc, server)
	client := traits.NewEmergencyApiClient(conn)
	return &ApiWrapper{
		EmergencyApiClient: client,
		server:             server,
		conn:               conn,
		desc:               traits.EmergencyApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.EmergencyApiClient

	server traits.EmergencyApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.EmergencyApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
