// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package metadata

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.MetadataApiServer	and presents it as a traits.MetadataApiClient
func WrapApi(server traits.MetadataApiServer) traits.MetadataApiClient {
	conn := wrap.ServerToClient(traits.MetadataApi_ServiceDesc, server)
	client := traits.NewMetadataApiClient(conn)
	return &apiWrapper{
		MetadataApiClient: client,
		server:            server,
	}
}

type apiWrapper struct {
	traits.MetadataApiClient

	server traits.MetadataApiServer
}

// compile time check that we implement the interface we need
var _ traits.MetadataApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.MetadataApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
