// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package metadata

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.MetadataInfoServer	and presents it as a traits.MetadataInfoClient
func WrapInfo(server traits.MetadataInfoServer) traits.MetadataInfoClient {
	conn := wrap.ServerToClient(traits.MetadataInfo_ServiceDesc, server)
	client := traits.NewMetadataInfoClient(conn)
	return &infoWrapper{
		MetadataInfoClient: client,
		server:             server,
	}
}

type infoWrapper struct {
	traits.MetadataInfoClient

	server traits.MetadataInfoServer
}

// compile time check that we implement the interface we need
var _ traits.MetadataInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.MetadataInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
