// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package channelpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ChannelInfoServer	and presents it as a traits.ChannelInfoClient
func WrapInfo(server traits.ChannelInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.ChannelInfo_ServiceDesc, server)
	client := traits.NewChannelInfoClient(conn)
	return &InfoWrapper{
		ChannelInfoClient: client,
		server:            server,
		conn:              conn,
		desc:              traits.ChannelInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.ChannelInfoClient

	server traits.ChannelInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.ChannelInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
