// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package extendretract

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.ExtendRetractApiServer	and presents it as a traits.ExtendRetractApiClient
func WrapApi(server traits.ExtendRetractApiServer) traits.ExtendRetractApiClient {
	conn := wrap.ServerToClient(traits.ExtendRetractApi_ServiceDesc, server)
	client := traits.NewExtendRetractApiClient(conn)
	return &apiWrapper{
		ExtendRetractApiClient: client,
		server:                 server,
	}
}

type apiWrapper struct {
	traits.ExtendRetractApiClient

	server traits.ExtendRetractApiServer
}

// compile time check that we implement the interface we need
var _ traits.ExtendRetractApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.ExtendRetractApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
