// Code generated by protoc-gen-router. DO NOT EDIT.

package extendretract

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.ExtendRetractInfoServer that allows routing named requests to specific traits.ExtendRetractInfoClient
type InfoRouter struct {
	traits.UnimplementedExtendRetractInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.ExtendRetractInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithExtendRetractInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithExtendRetractInfoClientFactory(f func(name string) (traits.ExtendRetractInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterExtendRetractInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.ExtendRetractInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.ExtendRetractInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.ExtendRetractInfoClient)
	return ok
}

func (r *InfoRouter) AddExtendRetractInfoClient(name string, client traits.ExtendRetractInfoClient) traits.ExtendRetractInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ExtendRetractInfoClient)
}

func (r *InfoRouter) RemoveExtendRetractInfoClient(name string) traits.ExtendRetractInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ExtendRetractInfoClient)
}

func (r *InfoRouter) GetExtendRetractInfoClient(name string) (traits.ExtendRetractInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ExtendRetractInfoClient), nil
}

func (r *InfoRouter) DescribeExtension(ctx context.Context, request *traits.DescribeExtensionRequest) (*traits.ExtensionSupport, error) {
	child, err := r.GetExtendRetractInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeExtension(ctx, request)
}
