// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package extendretract

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ExtendRetractInfoServer	and presents it as a traits.ExtendRetractInfoClient
func WrapInfo(server traits.ExtendRetractInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.ExtendRetractInfo_ServiceDesc, server)
	client := traits.NewExtendRetractInfoClient(conn)
	return &InfoWrapper{
		ExtendRetractInfoClient: client,
		server:                  server,
		conn:                    conn,
		desc:                    traits.ExtendRetractInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.ExtendRetractInfoClient

	server traits.ExtendRetractInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.ExtendRetractInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
