// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package extendretract

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.ExtendRetractInfoServer	and presents it as a traits.ExtendRetractInfoClient
func WrapInfo(server traits.ExtendRetractInfoServer) traits.ExtendRetractInfoClient {
	conn := wrap.ServerToClient(traits.ExtendRetractInfo_ServiceDesc, server)
	client := traits.NewExtendRetractInfoClient(conn)
	return &infoWrapper{
		ExtendRetractInfoClient: client,
		server:                  server,
	}
}

type infoWrapper struct {
	traits.ExtendRetractInfoClient

	server traits.ExtendRetractInfoServer
}

// compile time check that we implement the interface we need
var _ traits.ExtendRetractInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.ExtendRetractInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
