// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package extendretract

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ExtendRetractInfoServer	and presents it as a traits.ExtendRetractInfoClient
func WrapInfo(server traits.ExtendRetractInfoServer) traits.ExtendRetractInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.ExtendRetractInfoServer
}

// compile time check that we implement the interface we need
var _ traits.ExtendRetractInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.ExtendRetractInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() interface{} {
	return w.UnwrapServer()
}

func (w *infoWrapper) DescribeExtension(ctx context.Context, req *traits.DescribeExtensionRequest, _ ...grpc.CallOption) (*traits.ExtensionSupport, error) {
	return w.server.DescribeExtension(ctx, req)
}
