// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package speakerpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.SpeakerApiServer	and presents it as a traits.SpeakerApiClient
func WrapApi(server traits.SpeakerApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.SpeakerApi_ServiceDesc, server)
	client := traits.NewSpeakerApiClient(conn)
	return &ApiWrapper{
		SpeakerApiClient: client,
		server:           server,
		conn:             conn,
		desc:             traits.SpeakerApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.SpeakerApiClient

	server traits.SpeakerApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.SpeakerApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
