// Code generated by protoc-gen-router. DO NOT EDIT.

package fanspeedpb

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.FanSpeedInfoServer that allows routing named requests to specific traits.FanSpeedInfoClient
type InfoRouter struct {
	traits.UnimplementedFanSpeedInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.FanSpeedInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithFanSpeedInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithFanSpeedInfoClientFactory(f func(name string) (traits.FanSpeedInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterFanSpeedInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.FanSpeedInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.FanSpeedInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.FanSpeedInfoClient)
	return ok
}

func (r *InfoRouter) AddFanSpeedInfoClient(name string, client traits.FanSpeedInfoClient) traits.FanSpeedInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.FanSpeedInfoClient)
}

func (r *InfoRouter) RemoveFanSpeedInfoClient(name string) traits.FanSpeedInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.FanSpeedInfoClient)
}

func (r *InfoRouter) GetFanSpeedInfoClient(name string) (traits.FanSpeedInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.FanSpeedInfoClient), nil
}

func (r *InfoRouter) DescribeFanSpeed(ctx context.Context, request *traits.DescribeFanSpeedRequest) (*traits.FanSpeedSupport, error) {
	child, err := r.GetFanSpeedInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeFanSpeed(ctx, request)
}
