// Code generated by protoc-gen-router. DO NOT EDIT.

package color

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.ColorApiServer that allows routing named requests to specific traits.ColorApiClient
type ApiRouter struct {
	traits.UnimplementedColorApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.ColorApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithColorApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithColorApiClientFactory(f func(name string) (traits.ColorApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterColorApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.ColorApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.ColorApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(traits.ColorApiClient)
	return ok
}

func (r *ApiRouter) AddColorApiClient(name string, client traits.ColorApiClient) traits.ColorApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ColorApiClient)
}

func (r *ApiRouter) RemoveColorApiClient(name string) traits.ColorApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ColorApiClient)
}

func (r *ApiRouter) GetColorApiClient(name string) (traits.ColorApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ColorApiClient), nil
}

func (r *ApiRouter) GetColor(ctx context.Context, request *traits.GetColorRequest) (*traits.Color, error) {
	child, err := r.GetColorApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetColor(ctx, request)
}

func (r *ApiRouter) UpdateColor(ctx context.Context, request *traits.UpdateColorRequest) (*traits.Color, error) {
	child, err := r.GetColorApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateColor(ctx, request)
}

func (r *ApiRouter) PullColor(request *traits.PullColorRequest, server traits.ColorApi_PullColorServer) error {
	child, err := r.GetColorApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullColor(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullColorResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
