// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package color

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ColorInfoServer	and presents it as a traits.ColorInfoClient
func WrapInfo(server traits.ColorInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.ColorInfo_ServiceDesc, server)
	client := traits.NewColorInfoClient(conn)
	return &InfoWrapper{
		ColorInfoClient: client,
		server:          server,
		conn:            conn,
		desc:            traits.ColorInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.ColorInfoClient

	server traits.ColorInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.ColorInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
