// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package wastepb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.WasteInfoServer	and presents it as a traits.WasteInfoClient
func WrapInfo(server traits.WasteInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.WasteInfo_ServiceDesc, server)
	client := traits.NewWasteInfoClient(conn)
	return &InfoWrapper{
		WasteInfoClient: client,
		server:          server,
		conn:            conn,
		desc:            traits.WasteInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.WasteInfoClient

	server traits.WasteInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.WasteInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
