// Code generated by protoc-gen-router. DO NOT EDIT.

package emergency

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.EmergencyApiServer that allows routing named requests to specific traits.EmergencyApiClient
type ApiRouter struct {
	traits.UnimplementedEmergencyApiServer

	router *router.Router
}

// compile time check that we implement the interface we need
var _ traits.EmergencyApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		router: router.NewRouter(opts...),
	}
}

// WithEmergencyApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithEmergencyApiClientFactory(f func(name string) (traits.EmergencyApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server *grpc.Server) {
	traits.RegisterEmergencyApiServer(server, r)
}

func (r *ApiRouter) Add(name string, client traits.EmergencyApiClient) traits.EmergencyApiClient {
	res := r.router.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.EmergencyApiClient)
}

func (r *ApiRouter) Remove(name string) traits.EmergencyApiClient {
	res := r.router.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.EmergencyApiClient)
}

func (r *ApiRouter) Has(name string) bool {
	return r.router.Has(name)
}

func (r *ApiRouter) Get(name string) (traits.EmergencyApiClient, error) {
	res, err := r.router.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.EmergencyApiClient), nil
}

func (r *ApiRouter) GetEmergency(ctx context.Context, request *traits.GetEmergencyRequest) (*traits.Emergency, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetEmergency(ctx, request)
}

func (r *ApiRouter) UpdateEmergency(ctx context.Context, request *traits.UpdateEmergencyRequest) (*traits.Emergency, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateEmergency(ctx, request)
}

func (r *ApiRouter) PullEmergency(request *traits.PullEmergencyRequest, server traits.EmergencyApi_PullEmergencyServer) error {
	child, err := r.Get(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullEmergency(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullEmergencyResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
