// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package emergency

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// Wrap Info	adapts a traits.EmergencyInfoServer	and presents it as a traits.EmergencyInfoClient
func WrapInfo(server traits.EmergencyInfoServer) traits.EmergencyInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.EmergencyInfoServer
}

// compile time check that we implement the interface we need
var _ traits.EmergencyInfoClient = (*infoWrapper)(nil)

func (w *infoWrapper) DescribeEmergency(ctx context.Context, req *traits.DescribeEmergencyRequest, _ ...grpc.CallOption) (*traits.EmergencySupport, error) {
	return w.server.DescribeEmergency(ctx, req)
}
