// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package motionsensor

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.MotionSensorApiServer	and presents it as a traits.MotionSensorApiClient
func WrapApi(server traits.MotionSensorApiServer) traits.MotionSensorApiClient {
	conn := wrap.ServerToClient(traits.MotionSensorApi_ServiceDesc, server)
	client := traits.NewMotionSensorApiClient(conn)
	return &apiWrapper{
		MotionSensorApiClient: client,
		server:                server,
	}
}

type apiWrapper struct {
	traits.MotionSensorApiClient

	server traits.MotionSensorApiServer
}

// compile time check that we implement the interface we need
var _ traits.MotionSensorApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.MotionSensorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
