// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package booking

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.BookingApiServer	and presents it as a traits.BookingApiClient
func WrapApi(server traits.BookingApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.BookingApi_ServiceDesc, server)
	client := traits.NewBookingApiClient(conn)
	return &ApiWrapper{
		BookingApiClient: client,
		server:           server,
		conn:             conn,
		desc:             traits.BookingApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.BookingApiClient

	server traits.BookingApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.BookingApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
