// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package booking

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.BookingInfoServer	and presents it as a traits.BookingInfoClient
func WrapInfo(server traits.BookingInfoServer) traits.BookingInfoClient {
	conn := wrap.ServerToClient(traits.BookingInfo_ServiceDesc, server)
	client := traits.NewBookingInfoClient(conn)
	return &infoWrapper{
		BookingInfoClient: client,
		server:            server,
	}
}

type infoWrapper struct {
	traits.BookingInfoClient

	server traits.BookingInfoServer
}

// compile time check that we implement the interface we need
var _ traits.BookingInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.BookingInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
