// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package onoffpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.OnOffApiServer	and presents it as a traits.OnOffApiClient
func WrapApi(server traits.OnOffApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.OnOffApi_ServiceDesc, server)
	client := traits.NewOnOffApiClient(conn)
	return &ApiWrapper{
		OnOffApiClient: client,
		server:         server,
		conn:           conn,
		desc:           traits.OnOffApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.OnOffApiClient

	server traits.OnOffApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.OnOffApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
