// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package onoffpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.OnOffInfoServer	and presents it as a traits.OnOffInfoClient
func WrapInfo(server traits.OnOffInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.OnOffInfo_ServiceDesc, server)
	client := traits.NewOnOffInfoClient(conn)
	return &InfoWrapper{
		OnOffInfoClient: client,
		server:          server,
		conn:            conn,
		desc:            traits.OnOffInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.OnOffInfoClient

	server traits.OnOffInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.OnOffInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
