// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package meter

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.MeterInfoServer	and presents it as a traits.MeterInfoClient
func WrapInfo(server traits.MeterInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.MeterInfo_ServiceDesc, server)
	client := traits.NewMeterInfoClient(conn)
	return &InfoWrapper{
		MeterInfoClient: client,
		server:          server,
		conn:            conn,
		desc:            traits.MeterInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.MeterInfoClient

	server traits.MeterInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.MeterInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
