// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package motionsensorpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.MotionSensorApiServer	and presents it as a traits.MotionSensorApiClient
func WrapApi(server traits.MotionSensorApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.MotionSensorApi_ServiceDesc, server)
	client := traits.NewMotionSensorApiClient(conn)
	return &ApiWrapper{
		MotionSensorApiClient: client,
		server:                server,
		conn:                  conn,
		desc:                  traits.MotionSensorApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.MotionSensorApiClient

	server traits.MotionSensorApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.MotionSensorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
