// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package ptz

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.PtzApiServer	and presents it as a traits.PtzApiClient
func WrapApi(server traits.PtzApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.PtzApi_ServiceDesc, server)
	client := traits.NewPtzApiClient(conn)
	return &ApiWrapper{
		PtzApiClient: client,
		server:       server,
		conn:         conn,
		desc:         traits.PtzApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.PtzApiClient

	server traits.PtzApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.PtzApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
