// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package ptz

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.PtzApiServer	and presents it as a traits.PtzApiClient
func WrapApi(server traits.PtzApiServer) traits.PtzApiClient {
	conn := wrap.ServerToClient(traits.PtzApi_ServiceDesc, server)
	client := traits.NewPtzApiClient(conn)
	return &apiWrapper{
		PtzApiClient: client,
		server:       server,
	}
}

type apiWrapper struct {
	traits.PtzApiClient

	server traits.PtzApiServer
}

// compile time check that we implement the interface we need
var _ traits.PtzApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.PtzApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
