// Code generated by protoc-gen-router. DO NOT EDIT.

package hail

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.HailApiServer that allows routing named requests to specific traits.HailApiClient
type ApiRouter struct {
	traits.UnimplementedHailApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.HailApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithHailApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithHailApiClientFactory(f func(name string) (traits.HailApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterHailApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.HailApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.HailApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(traits.HailApiClient)
	return ok
}

func (r *ApiRouter) AddHailApiClient(name string, client traits.HailApiClient) traits.HailApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.HailApiClient)
}

func (r *ApiRouter) RemoveHailApiClient(name string) traits.HailApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.HailApiClient)
}

func (r *ApiRouter) GetHailApiClient(name string) (traits.HailApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.HailApiClient), nil
}

func (r *ApiRouter) CreateHail(ctx context.Context, request *traits.CreateHailRequest) (*traits.Hail, error) {
	child, err := r.GetHailApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.CreateHail(ctx, request)
}

func (r *ApiRouter) GetHail(ctx context.Context, request *traits.GetHailRequest) (*traits.Hail, error) {
	child, err := r.GetHailApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetHail(ctx, request)
}

func (r *ApiRouter) UpdateHail(ctx context.Context, request *traits.UpdateHailRequest) (*traits.Hail, error) {
	child, err := r.GetHailApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateHail(ctx, request)
}

func (r *ApiRouter) DeleteHail(ctx context.Context, request *traits.DeleteHailRequest) (*traits.DeleteHailResponse, error) {
	child, err := r.GetHailApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DeleteHail(ctx, request)
}

func (r *ApiRouter) PullHail(request *traits.PullHailRequest, server traits.HailApi_PullHailServer) error {
	child, err := r.GetHailApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullHail(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullHailResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) ListHails(ctx context.Context, request *traits.ListHailsRequest) (*traits.ListHailsResponse, error) {
	child, err := r.GetHailApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ListHails(ctx, request)
}

func (r *ApiRouter) PullHails(request *traits.PullHailsRequest, server traits.HailApi_PullHailsServer) error {
	child, err := r.GetHailApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullHails(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullHailsResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
