// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package hail

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.HailApiServer	and presents it as a traits.HailApiClient
func WrapApi(server traits.HailApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.HailApi_ServiceDesc, server)
	client := traits.NewHailApiClient(conn)
	return &ApiWrapper{
		HailApiClient: client,
		server:        server,
		conn:          conn,
		desc:          traits.HailApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.HailApiClient

	server traits.HailApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.HailApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
