// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package hail

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.HailApiServer	and presents it as a traits.HailApiClient
func WrapApi(server traits.HailApiServer) traits.HailApiClient {
	conn := wrap.ServerToClient(traits.HailApi_ServiceDesc, server)
	client := traits.NewHailApiClient(conn)
	return &apiWrapper{
		HailApiClient: client,
		server:        server,
	}
}

type apiWrapper struct {
	traits.HailApiClient

	server traits.HailApiServer
}

// compile time check that we implement the interface we need
var _ traits.HailApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.HailApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
