// Code generated by protoc-gen-router. DO NOT EDIT.

package hail

import (
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.HailInfoServer that allows routing named requests to specific traits.HailInfoClient
type InfoRouter struct {
	traits.UnimplementedHailInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.HailInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithHailInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithHailInfoClientFactory(f func(name string) (traits.HailInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterHailInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.HailInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.HailInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.HailInfoClient)
	return ok
}

func (r *InfoRouter) AddHailInfoClient(name string, client traits.HailInfoClient) traits.HailInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.HailInfoClient)
}

func (r *InfoRouter) RemoveHailInfoClient(name string) traits.HailInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.HailInfoClient)
}

func (r *InfoRouter) GetHailInfoClient(name string) (traits.HailInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.HailInfoClient), nil
}
