// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package hail

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.HailInfoServer	and presents it as a traits.HailInfoClient
func WrapInfo(server traits.HailInfoServer) traits.HailInfoClient {
	conn := wrap.ServerToClient(traits.HailInfo_ServiceDesc, server)
	client := traits.NewHailInfoClient(conn)
	return &infoWrapper{
		HailInfoClient: client,
		server:         server,
	}
}

type infoWrapper struct {
	traits.HailInfoClient

	server traits.HailInfoServer
}

// compile time check that we implement the interface we need
var _ traits.HailInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.HailInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
