// Code generated by protoc-gen-router. DO NOT EDIT.

package count

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.CountApiServer that allows routing named requests to specific traits.CountApiClient
type ApiRouter struct {
	traits.UnimplementedCountApiServer

	router *router.Router
}

// compile time check that we implement the interface we need
var _ traits.CountApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		router: router.NewRouter(opts...),
	}
}

// WithCountApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithCountApiClientFactory(f func(name string) (traits.CountApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server *grpc.Server) {
	traits.RegisterCountApiServer(server, r)
}

func (r *ApiRouter) Add(name string, client traits.CountApiClient) traits.CountApiClient {
	res := r.router.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.CountApiClient)
}

func (r *ApiRouter) Remove(name string) traits.CountApiClient {
	res := r.router.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.CountApiClient)
}

func (r *ApiRouter) Has(name string) bool {
	return r.router.Has(name)
}

func (r *ApiRouter) Get(name string) (traits.CountApiClient, error) {
	res, err := r.router.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.CountApiClient), nil
}

func (r *ApiRouter) GetCount(ctx context.Context, request *traits.GetCountRequest) (*traits.Count, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetCount(ctx, request)
}

func (r *ApiRouter) ResetCount(ctx context.Context, request *traits.ResetCountRequest) (*traits.Count, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ResetCount(ctx, request)
}

func (r *ApiRouter) UpdateCount(ctx context.Context, request *traits.UpdateCountRequest) (*traits.Count, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateCount(ctx, request)
}

func (r *ApiRouter) PullCounts(request *traits.PullCountsRequest, server traits.CountApi_PullCountsServer) error {
	child, err := r.Get(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullCounts(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullCountsResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
