// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package count

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.CountApiServer	and presents it as a traits.CountApiClient
func WrapApi(server traits.CountApiServer) traits.CountApiClient {
	conn := wrap.ServerToClient(traits.CountApi_ServiceDesc, server)
	client := traits.NewCountApiClient(conn)
	return &apiWrapper{
		CountApiClient: client,
		server:         server,
	}
}

type apiWrapper struct {
	traits.CountApiClient

	server traits.CountApiServer
}

// compile time check that we implement the interface we need
var _ traits.CountApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.CountApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
