// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package count

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// Wrap Info	adapts a traits.CountInfoServer	and presents it as a traits.CountInfoClient
func WrapInfo(server traits.CountInfoServer) traits.CountInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.CountInfoServer
}

// compile time check that we implement the interface we need
var _ traits.CountInfoClient = (*infoWrapper)(nil)

func (w *infoWrapper) DescribeCount(ctx context.Context, req *traits.DescribeCountRequest, _ ...grpc.CallOption) (*traits.CountSupport, error) {
	return w.server.DescribeCount(ctx, req)
}
