// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package fanspeed

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.FanSpeedApiServer	and presents it as a traits.FanSpeedApiClient
func WrapApi(server traits.FanSpeedApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.FanSpeedApi_ServiceDesc, server)
	client := traits.NewFanSpeedApiClient(conn)
	return &ApiWrapper{
		FanSpeedApiClient: client,
		server:            server,
		conn:              conn,
		desc:              traits.FanSpeedApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.FanSpeedApiClient

	server traits.FanSpeedApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.FanSpeedApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
