// Code generated by protoc-gen-router. DO NOT EDIT.

package fanspeed

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.FanSpeedApiServer that allows routing named requests to specific traits.FanSpeedApiClient
type ApiRouter struct {
	traits.UnimplementedFanSpeedApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.FanSpeedApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithFanSpeedApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithFanSpeedApiClientFactory(f func(name string) (traits.FanSpeedApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server *grpc.Server) {
	traits.RegisterFanSpeedApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.FanSpeedApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.FanSpeedApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(traits.FanSpeedApiClient)
	return ok
}

func (r *ApiRouter) AddFanSpeedApiClient(name string, client traits.FanSpeedApiClient) traits.FanSpeedApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.FanSpeedApiClient)
}

func (r *ApiRouter) RemoveFanSpeedApiClient(name string) traits.FanSpeedApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.FanSpeedApiClient)
}

func (r *ApiRouter) GetFanSpeedApiClient(name string) (traits.FanSpeedApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.FanSpeedApiClient), nil
}

func (r *ApiRouter) GetFanSpeed(ctx context.Context, request *traits.GetFanSpeedRequest) (*traits.FanSpeed, error) {
	child, err := r.GetFanSpeedApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetFanSpeed(ctx, request)
}

func (r *ApiRouter) UpdateFanSpeed(ctx context.Context, request *traits.UpdateFanSpeedRequest) (*traits.FanSpeed, error) {
	child, err := r.GetFanSpeedApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateFanSpeed(ctx, request)
}

func (r *ApiRouter) PullFanSpeed(request *traits.PullFanSpeedRequest, server traits.FanSpeedApi_PullFanSpeedServer) error {
	child, err := r.GetFanSpeedApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullFanSpeed(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullFanSpeedResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) ReverseFanSpeedDirection(ctx context.Context, request *traits.ReverseFanSpeedDirectionRequest) (*traits.FanSpeed, error) {
	child, err := r.GetFanSpeedApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ReverseFanSpeedDirection(ctx, request)
}
