// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package fanspeed

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.FanSpeedApiServer	and presents it as a traits.FanSpeedApiClient
func WrapApi(server traits.FanSpeedApiServer) traits.FanSpeedApiClient {
	conn := wrap.ServerToClient(traits.FanSpeedApi_ServiceDesc, server)
	client := traits.NewFanSpeedApiClient(conn)
	return &apiWrapper{
		FanSpeedApiClient: client,
		server:            server,
	}
}

type apiWrapper struct {
	traits.FanSpeedApiClient

	server traits.FanSpeedApiServer
}

// compile time check that we implement the interface we need
var _ traits.FanSpeedApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.FanSpeedApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
