// Code generated by protoc-gen-router. DO NOT EDIT.

package meterpb

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.MeterInfoServer that allows routing named requests to specific traits.MeterInfoClient
type InfoRouter struct {
	traits.UnimplementedMeterInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.MeterInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithMeterInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithMeterInfoClientFactory(f func(name string) (traits.MeterInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterMeterInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.MeterInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.MeterInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.MeterInfoClient)
	return ok
}

func (r *InfoRouter) AddMeterInfoClient(name string, client traits.MeterInfoClient) traits.MeterInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.MeterInfoClient)
}

func (r *InfoRouter) RemoveMeterInfoClient(name string) traits.MeterInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.MeterInfoClient)
}

func (r *InfoRouter) GetMeterInfoClient(name string) (traits.MeterInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.MeterInfoClient), nil
}

func (r *InfoRouter) DescribeMeterReading(ctx context.Context, request *traits.DescribeMeterReadingRequest) (*traits.MeterReadingSupport, error) {
	child, err := r.GetMeterInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeMeterReading(ctx, request)
}
