// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package colorpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.ColorApiServer	and presents it as a traits.ColorApiClient
func WrapApi(server traits.ColorApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.ColorApi_ServiceDesc, server)
	client := traits.NewColorApiClient(conn)
	return &ApiWrapper{
		ColorApiClient: client,
		server:         server,
		conn:           conn,
		desc:           traits.ColorApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.ColorApiClient

	server traits.ColorApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.ColorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
