// Code generated by protoc-gen-router. DO NOT EDIT.

package energystoragepb

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.EnergyStorageInfoServer that allows routing named requests to specific traits.EnergyStorageInfoClient
type InfoRouter struct {
	traits.UnimplementedEnergyStorageInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.EnergyStorageInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithEnergyStorageInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithEnergyStorageInfoClientFactory(f func(name string) (traits.EnergyStorageInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterEnergyStorageInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.EnergyStorageInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.EnergyStorageInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.EnergyStorageInfoClient)
	return ok
}

func (r *InfoRouter) AddEnergyStorageInfoClient(name string, client traits.EnergyStorageInfoClient) traits.EnergyStorageInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.EnergyStorageInfoClient)
}

func (r *InfoRouter) RemoveEnergyStorageInfoClient(name string) traits.EnergyStorageInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.EnergyStorageInfoClient)
}

func (r *InfoRouter) GetEnergyStorageInfoClient(name string) (traits.EnergyStorageInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.EnergyStorageInfoClient), nil
}

func (r *InfoRouter) DescribeEnergyLevel(ctx context.Context, request *traits.DescribeEnergyLevelRequest) (*traits.EnergyLevelSupport, error) {
	child, err := r.GetEnergyStorageInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeEnergyLevel(ctx, request)
}
