// Code generated by protoc-gen-router. DO NOT EDIT.

package publicationpb

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.PublicationApiServer that allows routing named requests to specific traits.PublicationApiClient
type ApiRouter struct {
	traits.UnimplementedPublicationApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.PublicationApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithPublicationApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithPublicationApiClientFactory(f func(name string) (traits.PublicationApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterPublicationApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.PublicationApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.PublicationApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(traits.PublicationApiClient)
	return ok
}

func (r *ApiRouter) AddPublicationApiClient(name string, client traits.PublicationApiClient) traits.PublicationApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.PublicationApiClient)
}

func (r *ApiRouter) RemovePublicationApiClient(name string) traits.PublicationApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.PublicationApiClient)
}

func (r *ApiRouter) GetPublicationApiClient(name string) (traits.PublicationApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.PublicationApiClient), nil
}

func (r *ApiRouter) CreatePublication(ctx context.Context, request *traits.CreatePublicationRequest) (*traits.Publication, error) {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.CreatePublication(ctx, request)
}

func (r *ApiRouter) GetPublication(ctx context.Context, request *traits.GetPublicationRequest) (*traits.Publication, error) {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetPublication(ctx, request)
}

func (r *ApiRouter) UpdatePublication(ctx context.Context, request *traits.UpdatePublicationRequest) (*traits.Publication, error) {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdatePublication(ctx, request)
}

func (r *ApiRouter) DeletePublication(ctx context.Context, request *traits.DeletePublicationRequest) (*traits.Publication, error) {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DeletePublication(ctx, request)
}

func (r *ApiRouter) PullPublication(request *traits.PullPublicationRequest, server traits.PublicationApi_PullPublicationServer) error {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullPublication(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullPublicationResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) ListPublications(ctx context.Context, request *traits.ListPublicationsRequest) (*traits.ListPublicationsResponse, error) {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ListPublications(ctx, request)
}

func (r *ApiRouter) PullPublications(request *traits.PullPublicationsRequest, server traits.PublicationApi_PullPublicationsServer) error {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullPublications(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullPublicationsResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) AcknowledgePublication(ctx context.Context, request *traits.AcknowledgePublicationRequest) (*traits.Publication, error) {
	child, err := r.GetPublicationApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.AcknowledgePublication(ctx, request)
}
