// Code generated by protoc-gen-router. DO NOT EDIT.

package energystorage

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.EnergyStorageApiServer that allows routing named requests to specific traits.EnergyStorageApiClient
type ApiRouter struct {
	traits.UnimplementedEnergyStorageApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.EnergyStorageApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithEnergyStorageApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithEnergyStorageApiClientFactory(f func(name string) (traits.EnergyStorageApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server *grpc.Server) {
	traits.RegisterEnergyStorageApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.EnergyStorageApiClient.
func (r *ApiRouter) Add(name string, client interface{}) interface{} {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.EnergyStorageApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client interface{}) bool {
	_, ok := client.(traits.EnergyStorageApiClient)
	return ok
}

func (r *ApiRouter) AddEnergyStorageApiClient(name string, client traits.EnergyStorageApiClient) traits.EnergyStorageApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.EnergyStorageApiClient)
}

func (r *ApiRouter) RemoveEnergyStorageApiClient(name string) traits.EnergyStorageApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.EnergyStorageApiClient)
}

func (r *ApiRouter) GetEnergyStorageApiClient(name string) (traits.EnergyStorageApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.EnergyStorageApiClient), nil
}

func (r *ApiRouter) GetEnergyLevel(ctx context.Context, request *traits.GetEnergyLevelRequest) (*traits.EnergyLevel, error) {
	child, err := r.GetEnergyStorageApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetEnergyLevel(ctx, request)
}

func (r *ApiRouter) PullEnergyLevel(request *traits.PullEnergyLevelRequest, server traits.EnergyStorageApi_PullEnergyLevelServer) error {
	child, err := r.GetEnergyStorageApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullEnergyLevel(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullEnergyLevelResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) Charge(ctx context.Context, request *traits.ChargeRequest) (*traits.ChargeResponse, error) {
	child, err := r.GetEnergyStorageApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.Charge(ctx, request)
}
