// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package energystorage

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.EnergyStorageApiServer	and presents it as a traits.EnergyStorageApiClient
func WrapApi(server traits.EnergyStorageApiServer) traits.EnergyStorageApiClient {
	conn := wrap.ServerToClient(traits.EnergyStorageApi_ServiceDesc, server)
	client := traits.NewEnergyStorageApiClient(conn)
	return &apiWrapper{
		EnergyStorageApiClient: client,
		server:                 server,
	}
}

type apiWrapper struct {
	traits.EnergyStorageApiClient

	server traits.EnergyStorageApiServer
}

// compile time check that we implement the interface we need
var _ traits.EnergyStorageApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.EnergyStorageApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
