// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package energystorage

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.EnergyStorageApiServer	and presents it as a traits.EnergyStorageApiClient
func WrapApi(server traits.EnergyStorageApiServer) traits.EnergyStorageApiClient {
	return &apiWrapper{server}
}

type apiWrapper struct {
	server traits.EnergyStorageApiServer
}

// compile time check that we implement the interface we need
var _ traits.EnergyStorageApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.EnergyStorageApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() interface{} {
	return w.UnwrapServer()
}

func (w *apiWrapper) GetEnergyLevel(ctx context.Context, req *traits.GetEnergyLevelRequest, _ ...grpc.CallOption) (*traits.EnergyLevel, error) {
	return w.server.GetEnergyLevel(ctx, req)
}

func (w *apiWrapper) PullEnergyLevel(ctx context.Context, in *traits.PullEnergyLevelRequest, opts ...grpc.CallOption) (traits.EnergyStorageApi_PullEnergyLevelClient, error) {
	stream := wrap.NewClientServerStream(ctx)
	server := &pullEnergyLevelApiServerWrapper{stream.Server()}
	client := &pullEnergyLevelApiClientWrapper{stream.Client()}
	go func() {
		err := w.server.PullEnergyLevel(in, server)
		stream.Close(err)
	}()
	return client, nil
}

type pullEnergyLevelApiClientWrapper struct {
	grpc.ClientStream
}

func (w *pullEnergyLevelApiClientWrapper) Recv() (*traits.PullEnergyLevelResponse, error) {
	m := new(traits.PullEnergyLevelResponse)
	if err := w.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

type pullEnergyLevelApiServerWrapper struct {
	grpc.ServerStream
}

func (s *pullEnergyLevelApiServerWrapper) Send(response *traits.PullEnergyLevelResponse) error {
	return s.ServerStream.SendMsg(response)
}

func (w *apiWrapper) Charge(ctx context.Context, req *traits.ChargeRequest, _ ...grpc.CallOption) (*traits.ChargeResponse, error) {
	return w.server.Charge(ctx, req)
}
