// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package energystorage

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.EnergyStorageInfoServer	and presents it as a traits.EnergyStorageInfoClient
func WrapInfo(server traits.EnergyStorageInfoServer) traits.EnergyStorageInfoClient {
	conn := wrap.ServerToClient(traits.EnergyStorageInfo_ServiceDesc, server)
	client := traits.NewEnergyStorageInfoClient(conn)
	return &infoWrapper{
		EnergyStorageInfoClient: client,
		server:                  server,
	}
}

type infoWrapper struct {
	traits.EnergyStorageInfoClient

	server traits.EnergyStorageInfoServer
}

// compile time check that we implement the interface we need
var _ traits.EnergyStorageInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.EnergyStorageInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
