// Code generated by protoc-gen-router. DO NOT EDIT.

package vendingpb

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.VendingApiServer that allows routing named requests to specific traits.VendingApiClient
type ApiRouter struct {
	traits.UnimplementedVendingApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.VendingApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithVendingApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithVendingApiClientFactory(f func(name string) (traits.VendingApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server grpc.ServiceRegistrar) {
	traits.RegisterVendingApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.VendingApiClient.
func (r *ApiRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.VendingApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client any) bool {
	_, ok := client.(traits.VendingApiClient)
	return ok
}

func (r *ApiRouter) AddVendingApiClient(name string, client traits.VendingApiClient) traits.VendingApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.VendingApiClient)
}

func (r *ApiRouter) RemoveVendingApiClient(name string) traits.VendingApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.VendingApiClient)
}

func (r *ApiRouter) GetVendingApiClient(name string) (traits.VendingApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.VendingApiClient), nil
}

func (r *ApiRouter) ListConsumables(ctx context.Context, request *traits.ListConsumablesRequest) (*traits.ListConsumablesResponse, error) {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ListConsumables(ctx, request)
}

func (r *ApiRouter) PullConsumables(request *traits.PullConsumablesRequest, server traits.VendingApi_PullConsumablesServer) error {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullConsumables(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullConsumablesResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) GetStock(ctx context.Context, request *traits.GetStockRequest) (*traits.Consumable_Stock, error) {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetStock(ctx, request)
}

func (r *ApiRouter) UpdateStock(ctx context.Context, request *traits.UpdateStockRequest) (*traits.Consumable_Stock, error) {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateStock(ctx, request)
}

func (r *ApiRouter) PullStock(request *traits.PullStockRequest, server traits.VendingApi_PullStockServer) error {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullStock(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullStockResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) ListInventory(ctx context.Context, request *traits.ListInventoryRequest) (*traits.ListInventoryResponse, error) {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.ListInventory(ctx, request)
}

func (r *ApiRouter) PullInventory(request *traits.PullInventoryRequest, server traits.VendingApi_PullInventoryServer) error {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullInventory(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullInventoryResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}

func (r *ApiRouter) Dispense(ctx context.Context, request *traits.DispenseRequest) (*traits.Consumable_Stock, error) {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.Dispense(ctx, request)
}

func (r *ApiRouter) StopDispense(ctx context.Context, request *traits.StopDispenseRequest) (*traits.Consumable_Stock, error) {
	child, err := r.GetVendingApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.StopDispense(ctx, request)
}
