// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package vendingpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.VendingInfoServer	and presents it as a traits.VendingInfoClient
func WrapInfo(server traits.VendingInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.VendingInfo_ServiceDesc, server)
	client := traits.NewVendingInfoClient(conn)
	return &InfoWrapper{
		VendingInfoClient: client,
		server:            server,
		conn:              conn,
		desc:              traits.VendingInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.VendingInfoClient

	server traits.VendingInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.VendingInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
