// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package lockunlock

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.LockUnlockApiServer	and presents it as a traits.LockUnlockApiClient
func WrapApi(server traits.LockUnlockApiServer) traits.LockUnlockApiClient {
	conn := wrap.ServerToClient(traits.LockUnlockApi_ServiceDesc, server)
	client := traits.NewLockUnlockApiClient(conn)
	return &apiWrapper{
		LockUnlockApiClient: client,
		server:              server,
	}
}

type apiWrapper struct {
	traits.LockUnlockApiClient

	server traits.LockUnlockApiServer
}

// compile time check that we implement the interface we need
var _ traits.LockUnlockApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.LockUnlockApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
