// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package lockunlock

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.LockUnlockInfoServer	and presents it as a traits.LockUnlockInfoClient
func WrapInfo(server traits.LockUnlockInfoServer) traits.LockUnlockInfoClient {
	conn := wrap.ServerToClient(traits.LockUnlockInfo_ServiceDesc, server)
	client := traits.NewLockUnlockInfoClient(conn)
	return &infoWrapper{
		LockUnlockInfoClient: client,
		server:               server,
	}
}

type infoWrapper struct {
	traits.LockUnlockInfoClient

	server traits.LockUnlockInfoServer
}

// compile time check that we implement the interface we need
var _ traits.LockUnlockInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.LockUnlockInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
