// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package inputselectpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.InputSelectApiServer	and presents it as a traits.InputSelectApiClient
func WrapApi(server traits.InputSelectApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.InputSelectApi_ServiceDesc, server)
	client := traits.NewInputSelectApiClient(conn)
	return &ApiWrapper{
		InputSelectApiClient: client,
		server:               server,
		conn:                 conn,
		desc:                 traits.InputSelectApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.InputSelectApiClient

	server traits.InputSelectApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.InputSelectApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
