// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package onoff

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.OnOffApiServer	and presents it as a traits.OnOffApiClient
func WrapApi(server traits.OnOffApiServer) traits.OnOffApiClient {
	conn := wrap.ServerToClient(traits.OnOffApi_ServiceDesc, server)
	client := traits.NewOnOffApiClient(conn)
	return &apiWrapper{
		OnOffApiClient: client,
		server:         server,
	}
}

type apiWrapper struct {
	traits.OnOffApiClient

	server traits.OnOffApiServer
}

// compile time check that we implement the interface we need
var _ traits.OnOffApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.OnOffApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
