// Code generated by protoc-gen-router. DO NOT EDIT.

package onoff

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
	io "io"
)

// ApiRouter is a traits.OnOffApiServer that allows routing named requests to specific traits.OnOffApiClient
type ApiRouter struct {
	traits.UnimplementedOnOffApiServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.OnOffApiServer = (*ApiRouter)(nil)

func NewApiRouter(opts ...router.Option) *ApiRouter {
	return &ApiRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithOnOffApiClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithOnOffApiClientFactory(f func(name string) (traits.OnOffApiClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *ApiRouter) Register(server *grpc.Server) {
	traits.RegisterOnOffApiServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.OnOffApiClient.
func (r *ApiRouter) Add(name string, client interface{}) interface{} {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.OnOffApiClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *ApiRouter) HoldsType(client interface{}) bool {
	_, ok := client.(traits.OnOffApiClient)
	return ok
}

func (r *ApiRouter) AddOnOffApiClient(name string, client traits.OnOffApiClient) traits.OnOffApiClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.OnOffApiClient)
}

func (r *ApiRouter) RemoveOnOffApiClient(name string) traits.OnOffApiClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.OnOffApiClient)
}

func (r *ApiRouter) GetOnOffApiClient(name string) (traits.OnOffApiClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.OnOffApiClient), nil
}

func (r *ApiRouter) GetOnOff(ctx context.Context, request *traits.GetOnOffRequest) (*traits.OnOff, error) {
	child, err := r.GetOnOffApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.GetOnOff(ctx, request)
}

func (r *ApiRouter) UpdateOnOff(ctx context.Context, request *traits.UpdateOnOffRequest) (*traits.OnOff, error) {
	child, err := r.GetOnOffApiClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.UpdateOnOff(ctx, request)
}

func (r *ApiRouter) PullOnOff(request *traits.PullOnOffRequest, server traits.OnOffApi_PullOnOffServer) error {
	child, err := r.GetOnOffApiClient(request.Name)
	if err != nil {
		return err
	}

	// so we can cancel our forwarding request if we can't send responses to our caller
	reqCtx, reqDone := context.WithCancel(server.Context())
	// issue the request
	stream, err := child.PullOnOff(reqCtx, request)
	if err != nil {
		return err
	}

	// send the stream header
	header, err := stream.Header()
	if err != nil {
		return err
	}
	if err = server.SendHeader(header); err != nil {
		return err
	}

	// send all the messages
	// false means the error is from the child, true means the error is from the caller
	var callerError bool
	for {
		// Impl note: we could improve throughput here by issuing the Recv and Send in different goroutines, but we're doing
		// it synchronously until we have a need to change the behaviour

		var msg *traits.PullOnOffResponse
		msg, err = stream.Recv()
		if err != nil {
			break
		}

		err = server.Send(msg)
		if err != nil {
			callerError = true
			break
		}
	}

	// err is guaranteed to be non-nil as it's the only way to exit the loop
	if callerError {
		// cancel the request
		reqDone()
		return err
	} else {
		if trailer := stream.Trailer(); trailer != nil {
			server.SetTrailer(trailer)
		}
		if err == io.EOF {
			return nil
		}
		return err
	}
}
