// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package mode

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.ModeApiServer	and presents it as a traits.ModeApiClient
func WrapApi(server traits.ModeApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.ModeApi_ServiceDesc, server)
	client := traits.NewModeApiClient(conn)
	return &ApiWrapper{
		ModeApiClient: client,
		server:        server,
		conn:          conn,
		desc:          traits.ModeApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.ModeApiClient

	server traits.ModeApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.ModeApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
