// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package mode

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ModeInfoServer	and presents it as a traits.ModeInfoClient
func WrapInfo(server traits.ModeInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.ModeInfo_ServiceDesc, server)
	client := traits.NewModeInfoClient(conn)
	return &InfoWrapper{
		ModeInfoClient: client,
		server:         server,
		conn:           conn,
		desc:           traits.ModeInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.ModeInfoClient

	server traits.ModeInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.ModeInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
