// Code generated by protoc-gen-router. DO NOT EDIT.

package mode

import (
	context "context"
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.ModeInfoServer that allows routing named requests to specific traits.ModeInfoClient
type InfoRouter struct {
	traits.UnimplementedModeInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.ModeInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithModeInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithModeInfoClientFactory(f func(name string) (traits.ModeInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (any, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterModeInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.ModeInfoClient.
func (r *InfoRouter) Add(name string, client any) any {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.ModeInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client any) bool {
	_, ok := client.(traits.ModeInfoClient)
	return ok
}

func (r *InfoRouter) AddModeInfoClient(name string, client traits.ModeInfoClient) traits.ModeInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ModeInfoClient)
}

func (r *InfoRouter) RemoveModeInfoClient(name string) traits.ModeInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ModeInfoClient)
}

func (r *InfoRouter) GetModeInfoClient(name string) (traits.ModeInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ModeInfoClient), nil
}

func (r *InfoRouter) DescribeModes(ctx context.Context, request *traits.DescribeModesRequest) (*traits.ModesSupport, error) {
	child, err := r.GetModeInfoClient(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeModes(ctx, request)
}
