// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package mode

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ModeInfoServer	and presents it as a traits.ModeInfoClient
func WrapInfo(server traits.ModeInfoServer) traits.ModeInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.ModeInfoServer
}

// compile time check that we implement the interface we need
var _ traits.ModeInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.ModeInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *infoWrapper) DescribeModes(ctx context.Context, req *traits.DescribeModesRequest, _ ...grpc.CallOption) (*traits.ModesSupport, error) {
	return w.server.DescribeModes(ctx, req)
}
