// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package speaker

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.SpeakerApiServer	and presents it as a traits.SpeakerApiClient
func WrapApi(server traits.SpeakerApiServer) traits.SpeakerApiClient {
	conn := wrap.ServerToClient(traits.SpeakerApi_ServiceDesc, server)
	client := traits.NewSpeakerApiClient(conn)
	return &apiWrapper{
		SpeakerApiClient: client,
		server:           server,
	}
}

type apiWrapper struct {
	traits.SpeakerApiClient

	server traits.SpeakerApiServer
}

// compile time check that we implement the interface we need
var _ traits.SpeakerApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.SpeakerApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
