// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package speaker

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.SpeakerInfoServer	and presents it as a traits.SpeakerInfoClient
func WrapInfo(server traits.SpeakerInfoServer) traits.SpeakerInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.SpeakerInfoServer
}

// compile time check that we implement the interface we need
var _ traits.SpeakerInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.SpeakerInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() interface{} {
	return w.UnwrapServer()
}

func (w *infoWrapper) DescribeVolume(ctx context.Context, req *traits.DescribeVolumeRequest, _ ...grpc.CallOption) (*traits.VolumeSupport, error) {
	return w.server.DescribeVolume(ctx, req)
}
