// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package enterleavesensor

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.EnterLeaveSensorApiServer	and presents it as a traits.EnterLeaveSensorApiClient
func WrapApi(server traits.EnterLeaveSensorApiServer) traits.EnterLeaveSensorApiClient {
	conn := wrap.ServerToClient(traits.EnterLeaveSensorApi_ServiceDesc, server)
	client := traits.NewEnterLeaveSensorApiClient(conn)
	return &apiWrapper{
		EnterLeaveSensorApiClient: client,
		server:                    server,
	}
}

type apiWrapper struct {
	traits.EnterLeaveSensorApiClient

	server traits.EnterLeaveSensorApiServer
}

// compile time check that we implement the interface we need
var _ traits.EnterLeaveSensorApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.EnterLeaveSensorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
