// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package enterleavesensor

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.EnterLeaveSensorInfoServer	and presents it as a traits.EnterLeaveSensorInfoClient
func WrapInfo(server traits.EnterLeaveSensorInfoServer) traits.EnterLeaveSensorInfoClient {
	conn := wrap.ServerToClient(traits.EnterLeaveSensorInfo_ServiceDesc, server)
	client := traits.NewEnterLeaveSensorInfoClient(conn)
	return &infoWrapper{
		EnterLeaveSensorInfoClient: client,
		server:                     server,
	}
}

type infoWrapper struct {
	traits.EnterLeaveSensorInfoClient

	server traits.EnterLeaveSensorInfoServer
}

// compile time check that we implement the interface we need
var _ traits.EnterLeaveSensorInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.EnterLeaveSensorInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
