// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package enterleavesensor

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
)

// WrapInfo	adapts a traits.EnterLeaveSensorInfoServer	and presents it as a traits.EnterLeaveSensorInfoClient
func WrapInfo(server traits.EnterLeaveSensorInfoServer) traits.EnterLeaveSensorInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.EnterLeaveSensorInfoServer
}

// compile time check that we implement the interface we need
var _ traits.EnterLeaveSensorInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.EnterLeaveSensorInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() interface{} {
	return w.UnwrapServer()
}
