// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package brightnesssensor

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.BrightnessSensorApiServer	and presents it as a traits.BrightnessSensorApiClient
func WrapApi(server traits.BrightnessSensorApiServer) traits.BrightnessSensorApiClient {
	conn := wrap.ServerToClient(traits.BrightnessSensorApi_ServiceDesc, server)
	client := traits.NewBrightnessSensorApiClient(conn)
	return &apiWrapper{
		BrightnessSensorApiClient: client,
		server:                    server,
	}
}

type apiWrapper struct {
	traits.BrightnessSensorApiClient

	server traits.BrightnessSensorApiServer
}

// compile time check that we implement the interface we need
var _ traits.BrightnessSensorApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.BrightnessSensorApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
