// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package brightnesssensor

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.BrightnessSensorInfoServer	and presents it as a traits.BrightnessSensorInfoClient
func WrapInfo(server traits.BrightnessSensorInfoServer) traits.BrightnessSensorInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.BrightnessSensorInfoServer
}

// compile time check that we implement the interface we need
var _ traits.BrightnessSensorInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.BrightnessSensorInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() interface{} {
	return w.UnwrapServer()
}

func (w *infoWrapper) DescribeAmbientBrightness(ctx context.Context, req *traits.DescribeAmbientBrightnessRequest, _ ...grpc.CallOption) (*traits.AmbientBrightnessSupport, error) {
	return w.server.DescribeAmbientBrightness(ctx, req)
}
