// Code generated by protoc-gen-router. DO NOT EDIT.

package parent

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.ParentInfoServer that allows routing named requests to specific traits.ParentInfoClient
type InfoRouter struct {
	traits.UnimplementedParentInfoServer

	router *router.Router
}

// compile time check that we implement the interface we need
var _ traits.ParentInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		router: router.NewRouter(opts...),
	}
}

// WithParentInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithParentInfoClientFactory(f func(name string) (traits.ParentInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterParentInfoServer(server, r)
}

func (r *InfoRouter) Add(name string, client traits.ParentInfoClient) traits.ParentInfoClient {
	res := r.router.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ParentInfoClient)
}

func (r *InfoRouter) Remove(name string) traits.ParentInfoClient {
	res := r.router.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ParentInfoClient)
}

func (r *InfoRouter) Has(name string) bool {
	return r.router.Has(name)
}

func (r *InfoRouter) Get(name string) (traits.ParentInfoClient, error) {
	res, err := r.router.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ParentInfoClient), nil
}
