// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package parent

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
)

// Wrap Info	adapts a traits.ParentInfoServer	and presents it as a traits.ParentInfoClient
func WrapInfo(server traits.ParentInfoServer) traits.ParentInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.ParentInfoServer
}

// compile time check that we implement the interface we need
var _ traits.ParentInfoClient = (*infoWrapper)(nil)
