// Code generated by protoc-gen-router. DO NOT EDIT.

package parent

import (
	fmt "fmt"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.ParentInfoServer that allows routing named requests to specific traits.ParentInfoClient
type InfoRouter struct {
	traits.UnimplementedParentInfoServer

	router.Router
}

// compile time check that we implement the interface we need
var _ traits.ParentInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		Router: router.NewRouter(opts...),
	}
}

// WithParentInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithParentInfoClientFactory(f func(name string) (traits.ParentInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterParentInfoServer(server, r)
}

// Add extends Router.Add to panic if client is not of type traits.ParentInfoClient.
func (r *InfoRouter) Add(name string, client interface{}) interface{} {
	if !r.HoldsType(client) {
		panic(fmt.Sprintf("not correct type: client of type %T is not a traits.ParentInfoClient", client))
	}
	return r.Router.Add(name, client)
}

func (r *InfoRouter) HoldsType(client interface{}) bool {
	_, ok := client.(traits.ParentInfoClient)
	return ok
}

func (r *InfoRouter) AddParentInfoClient(name string, client traits.ParentInfoClient) traits.ParentInfoClient {
	res := r.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.ParentInfoClient)
}

func (r *InfoRouter) RemoveParentInfoClient(name string) traits.ParentInfoClient {
	res := r.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.ParentInfoClient)
}

func (r *InfoRouter) GetParentInfoClient(name string) (traits.ParentInfoClient, error) {
	res, err := r.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.ParentInfoClient), nil
}
