// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package openclosepb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.OpenCloseApiServer	and presents it as a traits.OpenCloseApiClient
func WrapApi(server traits.OpenCloseApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.OpenCloseApi_ServiceDesc, server)
	client := traits.NewOpenCloseApiClient(conn)
	return &ApiWrapper{
		OpenCloseApiClient: client,
		server:             server,
		conn:               conn,
		desc:               traits.OpenCloseApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.OpenCloseApiClient

	server traits.OpenCloseApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.OpenCloseApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
