// Code generated by protoc-gen-router. DO NOT EDIT.

package powersupply

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	router "github.com/smart-core-os/sc-golang/pkg/router"
	grpc "google.golang.org/grpc"
)

// InfoRouter is a traits.PowerSupplyInfoServer that allows routing named requests to specific traits.PowerSupplyInfoClient
type InfoRouter struct {
	traits.UnimplementedPowerSupplyInfoServer

	router *router.Router
}

// compile time check that we implement the interface we need
var _ traits.PowerSupplyInfoServer = (*InfoRouter)(nil)

func NewInfoRouter(opts ...router.Option) *InfoRouter {
	return &InfoRouter{
		router: router.NewRouter(opts...),
	}
}

// WithPowerSupplyInfoClientFactory instructs the router to create a new
// client the first time Get is called for that name.
func WithPowerSupplyInfoClientFactory(f func(name string) (traits.PowerSupplyInfoClient, error)) router.Option {
	return router.WithFactory(func(name string) (interface{}, error) {
		return f(name)
	})
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterPowerSupplyInfoServer(server, r)
}

func (r *InfoRouter) Add(name string, client traits.PowerSupplyInfoClient) traits.PowerSupplyInfoClient {
	res := r.router.Add(name, client)
	if res == nil {
		return nil
	}
	return res.(traits.PowerSupplyInfoClient)
}

func (r *InfoRouter) Remove(name string) traits.PowerSupplyInfoClient {
	res := r.router.Remove(name)
	if res == nil {
		return nil
	}
	return res.(traits.PowerSupplyInfoClient)
}

func (r *InfoRouter) Has(name string) bool {
	return r.router.Has(name)
}

func (r *InfoRouter) Get(name string) (traits.PowerSupplyInfoClient, error) {
	res, err := r.router.Get(name)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(traits.PowerSupplyInfoClient), nil
}

func (r *InfoRouter) DescribePowerCapacity(ctx context.Context, request *traits.DescribePowerCapacityRequest) (*traits.PowerCapacitySupport, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribePowerCapacity(ctx, request)
}

func (r *InfoRouter) DescribeDrawNotification(ctx context.Context, request *traits.DescribeDrawNotificationRequest) (*traits.DrawNotificationSupport, error) {
	child, err := r.Get(request.Name)
	if err != nil {
		return nil, err
	}

	return child.DescribeDrawNotification(ctx, request)
}
