// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package vending

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.VendingApiServer	and presents it as a traits.VendingApiClient
func WrapApi(server traits.VendingApiServer) traits.VendingApiClient {
	conn := wrap.ServerToClient(traits.VendingApi_ServiceDesc, server)
	client := traits.NewVendingApiClient(conn)
	return &apiWrapper{
		VendingApiClient: client,
		server:           server,
	}
}

type apiWrapper struct {
	traits.VendingApiClient

	server traits.VendingApiServer
}

// compile time check that we implement the interface we need
var _ traits.VendingApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.VendingApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
