// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package electric

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapApi	adapts a traits.ElectricApiServer	and presents it as a traits.ElectricApiClient
func WrapApi(server traits.ElectricApiServer) traits.ElectricApiClient {
	conn := wrap.ServerToClient(traits.ElectricApi_ServiceDesc, server)
	client := traits.NewElectricApiClient(conn)
	return &apiWrapper{
		ElectricApiClient: client,
		server:            server,
	}
}

type apiWrapper struct {
	traits.ElectricApiClient

	server traits.ElectricApiServer
}

// compile time check that we implement the interface we need
var _ traits.ElectricApiClient = (*apiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *apiWrapper) UnwrapServer() traits.ElectricApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *apiWrapper) Unwrap() any {
	return w.UnwrapServer()
}
