// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package electric

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapInfo	adapts a traits.ElectricInfoServer	and presents it as a traits.ElectricInfoClient
func WrapInfo(server traits.ElectricInfoServer) *InfoWrapper {
	conn := wrap.ServerToClient(traits.ElectricInfo_ServiceDesc, server)
	client := traits.NewElectricInfoClient(conn)
	return &InfoWrapper{
		ElectricInfoClient: client,
		server:             server,
		conn:               conn,
		desc:               traits.ElectricInfo_ServiceDesc,
	}
}

type InfoWrapper struct {
	traits.ElectricInfoClient

	server traits.ElectricInfoServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *InfoWrapper) UnwrapServer() traits.ElectricInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *InfoWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *InfoWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
