// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package electric

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
)

// WrapInfo	adapts a traits.ElectricInfoServer	and presents it as a traits.ElectricInfoClient
func WrapInfo(server traits.ElectricInfoServer) traits.ElectricInfoClient {
	conn := wrap.ServerToClient(traits.ElectricInfo_ServiceDesc, server)
	client := traits.NewElectricInfoClient(conn)
	return &infoWrapper{
		ElectricInfoClient: client,
		server:             server,
	}
}

type infoWrapper struct {
	traits.ElectricInfoClient

	server traits.ElectricInfoServer
}

// compile time check that we implement the interface we need
var _ traits.ElectricInfoClient = (*infoWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *infoWrapper) UnwrapServer() traits.ElectricInfoServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *infoWrapper) Unwrap() any {
	return w.UnwrapServer()
}
