// Code generated by protoc-gen-router. DO NOT EDIT.

package electric

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	sync "sync"
)

// InfoRouter is a traits.ElectricInfoServer that allows routing named requests to specific traits.ElectricInfoClient
type InfoRouter struct {
	traits.UnimplementedElectricInfoServer

	mu       sync.Mutex
	registry map[string]traits.ElectricInfoClient
	// Factory can be used to dynamically create api clients if requests come in for devices we haven't seen.
	Factory func(string) (traits.ElectricInfoClient, error)
}

// compile time check that we implement the interface we need
var _ traits.ElectricInfoServer = (*InfoRouter)(nil)

func NewInfoRouter() *InfoRouter {
	return &InfoRouter{
		registry: make(map[string]traits.ElectricInfoClient),
	}
}

func (r *InfoRouter) Register(server *grpc.Server) {
	traits.RegisterElectricInfoServer(server, r)
}

func (r *InfoRouter) Add(name string, client traits.ElectricInfoClient) traits.ElectricInfoClient {
	r.mu.Lock()
	defer r.mu.Unlock()
	old := r.registry[name]
	r.registry[name] = client
	return old
}

func (r *InfoRouter) Remove(name string) traits.ElectricInfoClient {
	r.mu.Lock()
	defer r.mu.Unlock()
	old := r.registry[name]
	delete(r.registry, name)
	return old
}

func (r *InfoRouter) Has(name string) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	_, exists := r.registry[name]
	return exists
}

func (r *InfoRouter) Get(name string) (traits.ElectricInfoClient, error) {
	r.mu.Lock()
	child, exists := r.registry[name]
	defer r.mu.Unlock()
	if !exists {
		if r.Factory != nil {
			child, err := r.Factory(name)
			if err != nil {
				return nil, err
			}
			r.registry[name] = child
			return child, nil
		}
		return nil, status.Error(codes.NotFound, name)
	}
	return child, nil
}
