// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package electric

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
)

// Wrap Info	adapts a traits.ElectricInfoServer	and presents it as a traits.ElectricInfoClient
func WrapInfo(server traits.ElectricInfoServer) traits.ElectricInfoClient {
	return &infoWrapper{server}
}

type infoWrapper struct {
	server traits.ElectricInfoServer
}

// compile time check that we implement the interface we need
var _ traits.ElectricInfoClient = (*infoWrapper)(nil)
