// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package electric

import (
	context "context"
	traits "github.com/smart-core-os/sc-api/go/traits"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// WrapMemorySettingsApi	adapts a MemorySettingsApiServer	and presents it as a MemorySettingsApiClient
func WrapMemorySettingsApi(server MemorySettingsApiServer) MemorySettingsApiClient {
	return &memorySettingsApiWrapper{server}
}

type memorySettingsApiWrapper struct {
	server MemorySettingsApiServer
}

// compile time check that we implement the interface we need
var _ MemorySettingsApiClient = (*memorySettingsApiWrapper)(nil)

// UnwrapServer returns the underlying server instance.
func (w *memorySettingsApiWrapper) UnwrapServer() MemorySettingsApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *memorySettingsApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *memorySettingsApiWrapper) UpdateDemand(ctx context.Context, req *UpdateDemandRequest, _ ...grpc.CallOption) (*traits.ElectricDemand, error) {
	return w.server.UpdateDemand(ctx, req)
}

func (w *memorySettingsApiWrapper) CreateMode(ctx context.Context, req *CreateModeRequest, _ ...grpc.CallOption) (*traits.ElectricMode, error) {
	return w.server.CreateMode(ctx, req)
}

func (w *memorySettingsApiWrapper) UpdateMode(ctx context.Context, req *UpdateModeRequest, _ ...grpc.CallOption) (*traits.ElectricMode, error) {
	return w.server.UpdateMode(ctx, req)
}

func (w *memorySettingsApiWrapper) DeleteMode(ctx context.Context, req *DeleteModeRequest, _ ...grpc.CallOption) (*emptypb.Empty, error) {
	return w.server.DeleteMode(ctx, req)
}
