// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package extendretractpb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.ExtendRetractApiServer	and presents it as a traits.ExtendRetractApiClient
func WrapApi(server traits.ExtendRetractApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.ExtendRetractApi_ServiceDesc, server)
	client := traits.NewExtendRetractApiClient(conn)
	return &ApiWrapper{
		ExtendRetractApiClient: client,
		server:                 server,
		conn:                   conn,
		desc:                   traits.ExtendRetractApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.ExtendRetractApiClient

	server traits.ExtendRetractApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.ExtendRetractApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
