name: Go Test
on:
  push:
    branches: [main]

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Run tests
      run: go test -v ./...

    - name: Run short tests with race detector
      run: go test -v -short -race ./...