// Code generated by protoc-gen-wrapper. DO NOT EDIT.

package accesspb

import (
	traits "github.com/smart-core-os/sc-api/go/traits"
	wrap "github.com/smart-core-os/sc-golang/pkg/wrap"
	grpc "google.golang.org/grpc"
)

// WrapApi	adapts a traits.AccessApiServer	and presents it as a traits.AccessApiClient
func WrapApi(server traits.AccessApiServer) *ApiWrapper {
	conn := wrap.ServerToClient(traits.AccessApi_ServiceDesc, server)
	client := traits.NewAccessApiClient(conn)
	return &ApiWrapper{
		AccessApiClient: client,
		server:          server,
		conn:            conn,
		desc:            traits.AccessApi_ServiceDesc,
	}
}

type ApiWrapper struct {
	traits.AccessApiClient

	server traits.AccessApiServer
	conn   grpc.ClientConnInterface
	desc   grpc.ServiceDesc
}

// UnwrapServer returns the underlying server instance.
func (w *ApiWrapper) UnwrapServer() traits.AccessApiServer {
	return w.server
}

// Unwrap implements wrap.Unwrapper and returns the underlying server instance as an unknown type.
func (w *ApiWrapper) Unwrap() any {
	return w.UnwrapServer()
}

func (w *ApiWrapper) UnwrapService() (grpc.ClientConnInterface, grpc.ServiceDesc) {
	return w.conn, w.desc
}
